apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-api-sa
  namespace: task-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-runner-role
  namespace: task-runner
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - create
      - get
      - list
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-runner-rb
  namespace: task-runner
subjects:
  - kind: ServiceAccount
    name: task-api-sa
    namespace: task-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-runner-role

